services:
  - type: web
    name: emotion-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
    rootDir: backend

  - type: web
    name: emotion-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - frontend/**
    rootDir: frontend
